<?php
return array(
    'A01' => array(
        'name'        => 'Graha Pradipta Jogja Expo Center',
        'address'     => 'Jalan Raya Janti',
        'city'        => 'Yogyakarta',
        'country'     => 'ID',
        'state'       => 'YO',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.7994607,
        'longitude'   => 110.40448300000003,
        'place_id'    => 'ChIJK5Gh2V1Xei4RhKjn6woSAP4'
    ),
    'A02' => array(
        'name'        => 'Candi Prambanan',
        'address'     => 'Jalan Raya Solo, Prambanan',
        'city'        => 'Sleman',
        'country'     => 'ID',
        'state'       => 'YO',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.752020600000001,
        'longitude'   => 110.49146740000003,
        'place_id'    => 'ChIJ0VnY2-Naei4RLVqVJTug5xk'
    ),
    'A03' => array(
        'name'        => 'Candi Borobudur',
        'address'     => 'Borobudur',
        'city'        => 'Magelang',
        'country'     => 'ID',
        'state'       => 'JT',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.6078738,
        'longitude'   => 110.20375130000002,
        'place_id'    => 'ChIJl9anCfCMei4Ry8NNdDRD0w0'
    ),
    'A04' => array(
        'name'        => 'Keraton Yogyakarta',
        'address'     => 'Jalan Rotowijayan',
        'city'        => 'Yogyakarta',
        'country'     => 'ID',
        'state'       => 'YO',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.8052845,
        'longitude'   => 110.36420309999994,
        'place_id'    => 'ChIJ78cG25ZXei4RbCcrBc9xUjk'
    ),
    'A05' => array(
        'name'        => 'Grha Sabha Pramana UGM',
        'address'     => 'Catur Tunggal, Depok',
        'city'        => 'Sleman',
        'country'     => 'ID',
        'state'       => 'YO',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.7713847,
        'longitude'   => 110.37749980000001,
        'place_id'    => 'ChIJKZdy1LJZei4R5Pg0z197Taw'
    ),
    'A06' => array(
        'name'        => 'Jalan Malioboro',
        'address'     => 'Gedong Tengen',
        'city'        => 'Yogyakarta',
        'country'     => 'ID',
        'state'       => 'YO',
        'postal_code' => '123456',
        'phone'       => '(0274) 123456',
        'email'       => 'info@example.com',
        'website'     => 'http://www.example.com',
        'latitude'    => -7.792630600000001,
        'longitude'   => 110.36584419999997,
        'place_id'    => 'ChIJxQZh-iVYei4RMxHtpSHFpD4'
    ),
);